image: docker:latest

variables:
  GIT_CLEAN_FLAGS: none # disable git clean

services:
  - docker:dind

stages:
  - setup
  - build
  - deploy

step-setup:
  stage: setup
  before_script:
    - export DYNAMIC_ENV_VAR=PRODUCTION
  only:
    - master
  tags:
    - feedme-staging
  script:
    - echo setting up $DYNAMIC_ENV_VAR
    - touch .env
    - sudo cp .env.example .env
    - sudo docker image prune -f

step-build:
  stage: build
  only:
    - master
  tags:
    - feedme-staging
  script:
    - echo building $DYNAMIC_ENV_VAR
    - sudo docker-compose build --no-cache

step-deploy:
  stage: deploy
  only:
    - master
  tags:
    - feedme-staging
  script:
    - echo deploying $DYNAMIC_ENV_VAR
    - sudo docker-compose up -d
